baseurl: /
languageCode: en-us
title: Kang Zihao
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: â†©

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4
    - name: "Subscribe"
      url: "/index.xml"

params:
  description: "Welcom to my planet."
  footer: "&copy; [Kang Zihao](https://kangzihao.netlify.app) 2024-{Year} | [Github](https://github.com/catalpakzh) | [Twitter](https://x.com/Catalpakk)" 
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"
  
markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

enableEmoji: true